[package]
name = "bitpart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
itertools = "0.10.5"
rayon = "1.6.1"

[dev-dependencies]
criterion = "0.4"
sisap-data = { path = "sisap-data" }

[[bench]]
name = "benchmarks"
harness = false

[workspace]
members = [".", "sisap-data", "example"]
